# Generated by Django 3.1.1 on 2020-09-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del documento', max_length=150, unique=True, verbose_name='Nombre documento:')),
                ('dias', models.PositiveIntegerField(help_text='Ingrese el numero de dias', verbose_name='Numero de dias:')),
            ],
            options={
                'verbose_name': 'nombre',
                'verbose_name_plural': 'nombres',
                'ordering': ['nombre'],
            },
        ),
    ]
