# Generated by Django 3.1.1 on 2020-09-20 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del documento', max_length=150, unique=True, verbose_name='Nombre documento:')),
            ],
            options={
                'verbose_name': 'nombre',
                'verbose_name_plural': 'nombres',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Ingrese el tipo del documento', max_length=150, unique=True, verbose_name='Tipo documento:')),
                ('dias', models.PositiveIntegerField(help_text='Ingrese el numero de dias', verbose_name='Numero de dias:')),
            ],
            options={
                'verbose_name': 'tipo',
                'verbose_name_plural': 'tipos',
                'ordering': ['tipo'],
            },
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AddField(
            model_name='documento',
            name='id_tipo',
            field=models.ForeignKey(help_text='Ingrese el tipo del documento', on_delete=django.db.models.deletion.CASCADE, related_name='documento_tipo', to='documentos.tipo', verbose_name='tipo documento:'),
        ),
    ]
