# Generated by Django 3.1.1 on 2020-09-20 00:38

from django.db import migrations, models
import django.db.models.deletion
import documentos.models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_auto_20200919_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(help_text='Ingrese el correo electronico', max_length=150, verbose_name='Correo electronico:')),
                ('fecha_solicitud', models.DateTimeField(auto_now=True)),
                ('fecha_aprox', models.DateTimeField(default=documentos.models.in_few_days)),
                ('fecha_listo', models.DateTimeField(blank=True, null=True)),
                ('on_off', models.BooleanField(default=True, help_text='Inglese el estado de la solicitud', verbose_name='Solicitud Activa:')),
                ('id_documento', models.ForeignKey(help_text='Ingrese el documento', on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_documento', to='documentos.documento', verbose_name='documento:')),
            ],
            options={
                'verbose_name': 'correo',
                'verbose_name_plural': 'correos',
                'ordering': ['correo'],
            },
        ),
    ]
