# Generated by Django 3.1.1 on 2020-09-20 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_solicitud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['correo'], 'verbose_name': 'solicitud', 'verbose_name_plural': 'solicitudes'},
        ),
    ]
